import type { Client } from '../types';

/**
 * All monthlyFee values are Jan/Feb vintage (feeEstimated: true).
 * June booked ~$91K per Blueprint v2 — verify all fees before going live.
 * Clients without roster docs (St. Rocco's, Guidelines) are included with
 * null fees and marked pending.
 */
export const clients: Client[] = [
  // ── PAUL'S ACCOUNTS ───────────────────────────────────────────────────────

  {
    id: 'jason-freedman',
    name: 'Jason Freedman',
    tier: null,
    monthlyFee: 7_500,
    feeEstimated: true,
    accountManagerId: 'paul-kartelias',
    productionOwnerIds: ['austin'],
    billingDayOfMonth: 18,
    billingPaused: false,
    churnRisk: null,
    status: 'active',
    notes: 'Austin handles clips',
  },
  {
    id: 'calco-designs',
    name: 'Calco Designs',
    tier: null,
    monthlyFee: 10_000,
    feeEstimated: true,
    accountManagerId: 'paul-kartelias',
    productionOwnerIds: [],
    billingDayOfMonth: 8,
    billingPaused: false,
    churnRisk: null,
    status: 'active',
  },
  {
    id: 'penn-community-bank',
    name: 'Penn Community Bank',
    tier: null,
    monthlyFee: 6_500,
    feeEstimated: true,
    accountManagerId: 'paul-kartelias',
    productionOwnerIds: ['vince-cravero'],
    billingDayOfMonth: 7,
    billingPaused: false,
    churnRisk: null,
    status: 'active',
    notes: 'Vince: commercial spots + UGC',
  },
  {
    id: 'stark-stark',
    name: 'Stark & Stark',
    tier: null,
    monthlyFee: 3_500,
    feeEstimated: true,
    accountManagerId: 'paul-kartelias',
    productionOwnerIds: [],
    billingDayOfMonth: 21,
    billingPaused: false,
    churnRisk: null,
    status: 'pending',
    notes: 'Was awaiting signed agreement',
  },
  {
    id: 'accredited-roofing',
    name: 'Accredited Roofing',
    tier: null,
    monthlyFee: 2_500,
    feeEstimated: true,
    accountManagerId: 'paul-kartelias',
    productionOwnerIds: [],
    billingDayOfMonth: 9,
    billingPaused: false,
    churnRisk: null,
    status: 'active',
  },
  {
    id: 'heritage-landscape',
    name: 'Heritage Landscape',
    tier: null,
    monthlyFee: 2_500,
    feeEstimated: true,
    accountManagerId: 'paul-kartelias',
    productionOwnerIds: [],
    billingDayOfMonth: 28,
    billingPaused: false,
    churnRisk: null,
    status: 'active',
  },
  {
    id: 'brandon-rost-bemarketing',
    name: 'Brandon Rost / BeMarketing',
    aliases: ['BeMarketing'],
    tier: null,
    monthlyFee: 5_000,
    feeEstimated: true,
    accountManagerId: 'paul-kartelias',
    productionOwnerIds: [],
    billingDayOfMonth: null,
    billingPaused: false,
    churnRisk: null,
    status: 'active',
    notes: 'Ad management',
  },
  {
    id: 'anthony-hales',
    name: 'Anthony Hales',
    tier: null,
    monthlyFee: 5_000,
    feeEstimated: true,
    accountManagerId: 'paul-kartelias',
    productionOwnerIds: [],
    billingDayOfMonth: 7,
    billingPaused: false,
    churnRisk: null,
    status: 'active',
  },
  {
    id: 'munz-construction',
    name: 'Munz Construction',
    tier: null,
    monthlyFee: 1_500,
    feeEstimated: true,
    accountManagerId: 'paul-kartelias',
    productionOwnerIds: ['kaitlyn'],
    billingDayOfMonth: 22,
    billingPaused: false,
    churnRisk: null,
    status: 'active',
    notes: 'Kaitlyn: reels',
  },
  {
    id: 'big-bounce-america',
    name: 'Big Bounce America',
    tier: null,
    monthlyFee: null,
    campaignFee: 62_000,
    campaignFeeRemaining: 60_000,
    feeEstimated: true,
    accountManagerId: 'paul-kartelias',
    productionOwnerIds: ['brian-phillips', 'austin'],
    billingDayOfMonth: null,
    billingPaused: false,
    churnRisk: null,
    status: 'campaign',
    notes: 'Production paused 6/9. $62K total ($55K base + $10K TV); $60K remaining Philly budget. Positive-branding pivot; 3-tier funnel. Brian: statics, Austin: video.',
  },

  // ── SARA'S ACCOUNTS ───────────────────────────────────────────────────────

  {
    id: 'volkmann',
    name: 'Volkmann',
    tier: null,
    monthlyFee: 2_500,
    feeEstimated: true,
    accountManagerId: 'sara-weir',
    productionOwnerIds: ['vince-cravero', 'kaitlyn'],
    billingDayOfMonth: 1,
    billingPaused: false,
    churnRisk: null,
    status: 'active',
    notes: 'Vince: demos/ads. KO: reels. Next shoot pending client.',
  },
  {
    id: 'on2-wellness',
    name: 'On2 Wellness',
    tier: null,
    monthlyFee: 5_000,
    feeEstimated: true,
    adBudget: 1_500,
    accountManagerId: 'sara-weir',
    productionOwnerIds: ['austin', 'kartik'],
    billingDayOfMonth: 3,
    billingPaused: false,
    churnRisk: null,
    status: 'active',
    notes: 'Austin: reels/clips. Kartik: podcast. Ad launch 6/11 11am; $1,500/mo ad budget confirmed. Launch on hold pending Stripe/platform resolution. Healthy neutral.',
  },
  {
    id: 'chad-blankenbiller',
    name: 'Chad Blankenbiller',
    aliases: ['Chaddy Daddy'],
    tier: null,
    monthlyFee: null,
    feeEstimated: true,
    accountManagerId: 'sara-weir',
    productionOwnerIds: ['kaitlyn', 'austin'],
    billingDayOfMonth: null,
    billingPaused: false,
    churnRisk: null,
    status: 'active',
    contractEndDate: '2026-12-31',
    notes: 'Kaitlyn: statics. Austin: clips. Clip backlog; slow approvals. Contract ends ~Dec 2026.',
  },
  {
    id: 'modern-aesthetic',
    name: 'Modern Aesthetic',
    entities: ['Rejuvenation', 'Plastic Surgery'],
    tier: null,
    monthlyFee: null,
    feeEstimated: true,
    accountManagerId: 'sara-weir',
    productionOwnerIds: ['vince-cravero'],
    billingDayOfMonth: null,
    billingPaused: false,
    churnRisk: 'high',
    status: 'active',
    notes: 'Two legal entities (Rejuvenation + Plastic Surgery) with separate trackers. M2M. Relationship deteriorating — lost a month of content. Churn risk.',
  },
  {
    id: 'pat-sanaghan',
    name: 'Pat Sanaghan',
    aliases: ['A Year of Drinking Whiskey'],
    tier: null,
    monthlyFee: 2_500,
    feeEstimated: true,
    accountManagerId: 'sara-weir',
    productionOwnerIds: [],
    billingDayOfMonth: null,
    billingPaused: true,
    billingPausedReason: 'Unsigned SOW; billing paused ~2 months',
    churnRisk: null,
    status: 'paused',
    notes: 'Co-author session next week. Friday 6/12 9:30 call. SOP 25 14-day clock pending Matt sign-off.',
  },

  // ── PROJECT / VINCE-LED ────────────────────────────────────────────────────

  {
    id: 'stephen-fischer',
    name: 'Stephen Fischer',
    tier: null,
    monthlyFee: null,
    feeEstimated: true,
    accountManagerId: null,
    productionOwnerIds: ['vince-cravero'],
    billingDayOfMonth: null,
    billingPaused: false,
    churnRisk: null,
    status: 'campaign',
    notes: 'Vampire podcast + museum B-roll due Fri 6/12 (pushed early for Austin\'s travel)',
  },
  {
    id: 'st-roccos',
    name: 'St. Rocco\'s',
    tier: null,
    monthlyFee: null,
    feeEstimated: true,
    accountManagerId: null,
    productionOwnerIds: ['vince-cravero'],
    billingDayOfMonth: null,
    billingPaused: false,
    churnRisk: null,
    status: 'active',
    notes: 'Not in any roster doc. Verticals/spots out for revision.',
  },
  {
    id: 'guidelines',
    name: 'Guidelines',
    tier: null,
    monthlyFee: null,
    feeEstimated: true,
    accountManagerId: null,
    productionOwnerIds: ['vince-cravero'],
    billingDayOfMonth: null,
    billingPaused: false,
    churnRisk: null,
    status: 'pending',
    notes: 'Not in any roster doc. Blocked on inbound raw footage.',
  },

  // ── COMPLETE / UNCLEAR ────────────────────────────────────────────────────

  {
    id: 'gear-infusion',
    name: 'Gear Infusion',
    tier: null,
    monthlyFee: null,
    feeEstimated: false,
    accountManagerId: 'sara-weir',
    productionOwnerIds: ['vince-cravero'],
    billingDayOfMonth: null,
    billingPaused: false,
    churnRisk: null,
    status: 'complete',
    notes: 'Complete as of 6/4',
  },
  {
    id: 'timepiece',
    name: 'Timepiece',
    tier: null,
    monthlyFee: null,
    feeEstimated: true,
    accountManagerId: null,
    productionOwnerIds: ['austin'],
    billingDayOfMonth: null,
    billingPaused: false,
    churnRisk: null,
    status: 'active',
    notes: 'In PM doc; current status unclear',
  },
  {
    id: 'breezy-powerwash',
    name: 'Breezy Powerwash',
    tier: null,
    monthlyFee: null,
    feeEstimated: true,
    accountManagerId: null,
    productionOwnerIds: ['austin'],
    billingDayOfMonth: null,
    billingPaused: false,
    churnRisk: null,
    status: 'active',
    notes: 'In PM doc; current status unclear',
  },
  {
    id: 'jason-fermier',
    name: 'Jason Fermier',
    tier: null,
    monthlyFee: null,
    feeEstimated: true,
    accountManagerId: null,
    productionOwnerIds: ['austin'],
    billingDayOfMonth: null,
    billingPaused: false,
    churnRisk: null,
    status: 'active',
    notes: 'In PM doc; current status unclear',
  },
];
