import type { TeamMember } from '../types';

/**
 * Pay rates confirmed: Austin ($17/hr), Dustin ($500/wk), Matt ($10K/mo).
 * Kaitlyn's rate exists from the hours-tracker work — carry forward when retrieved.
 * All other pay rates are null (pending).
 * Availability null = pending for most team members.
 */
export const team: TeamMember[] = [
  {
    id: 'tim-ogrady',
    name: 'Tim O\'Grady',
    role: 'Director of Operations',
    appRole: 'Leadership',
    employmentType: 'FTEmployee',
    payRate: null,
    availability: 'FT',
  },
  {
    id: 'matt-freedman',
    name: 'Matt Freedman',
    role: 'Founder',
    appRole: 'Leadership',
    employmentType: 'Founder',
    payRate: { amount: 10_000, unit: 'monthly' },
    availability: 'FT',
  },
  {
    id: 'paul-kartelias',
    name: 'Paul Kartelias',
    role: 'Senior Account Lead',
    appRole: 'AccountManager',
    employmentType: null,
    payRate: null,
    availability: null,
  },
  {
    id: 'sara-weir',
    name: 'Sara Weir',
    role: 'Account Manager + Inbound Sales',
    appRole: 'AccountManager',
    employmentType: null,
    payRate: null,
    availability: null,
    notes: '≈2.5 accounts; moving to full-time sales',
  },
  {
    id: 'vince-cravero',
    name: 'Vince Cravero',
    role: 'Shooter / Corporate & Linear Editor',
    appRole: 'Team',
    employmentType: 'Contractor',
    payRate: null,
    availability: 'Constrained',
    contractorToFTDate: '2026-08-01',
    notes: 'Contractor → FT August 2026; second job winding down until then',
  },
  {
    id: 'austin',
    name: 'Austin',
    role: 'Lead Editor (Generalist)',
    appRole: 'Team',
    employmentType: 'PT',
    payRate: { amount: 17, unit: 'hourly' },
    availability: null,
    redlined: true,
    notes: 'Known redlined; traveling this week (6/10 week)',
  },
  {
    id: 'dustin-napoli',
    name: 'Dustin Napoli',
    role: 'Shooter / Clipper / Audio + Opus Captions',
    appRole: 'Team',
    employmentType: 'PT',
    payRate: { amount: 500, unit: 'weekly' },
    availability: null,
  },
  {
    id: 'kaitlyn',
    name: 'Kaitlyn',
    role: 'Social Media Manager + Static Editor',
    appRole: 'Team',
    employmentType: 'PT',
    payRate: null,
    availability: null,
    notes: 'Rate confirmed in earlier hours-tracker work — carry forward. Listed as "KO" in Sara\'s tracker.',
  },
  {
    id: 'eric',
    name: 'Eric',
    role: 'Editor',
    appRole: 'Team',
    employmentType: null,
    payRate: null,
    availability: null,
  },
  {
    id: 'kartik',
    name: 'Kartik',
    role: 'Full-Length Podcast Editor + Ads (Frame.io)',
    appRole: 'Team',
    employmentType: 'Freelance',
    payRate: null,
    availability: null,
    notes: 'Off podcast clipping per Vince. "Cardic" was a misspelling — merged to single person.',
  },
  {
    id: 'marko',
    name: 'Marko',
    role: 'Media Buyer',
    appRole: 'Team',
    employmentType: 'PT',
    payRate: null,
    availability: null,
  },
  {
    id: 'andrew',
    name: 'Andrew',
    role: 'Media Buyer',
    appRole: 'Team',
    employmentType: 'PT',
    payRate: null,
    availability: null,
  },
  {
    id: 'brian-phillips',
    name: 'Brian Phillips',
    role: 'Creative Direction',
    appRole: 'Team',
    employmentType: 'ProjectBased',
    payRate: null,
    availability: null,
  },
  {
    id: 'chris',
    name: 'Chris',
    role: 'Project-Based',
    appRole: 'Team',
    employmentType: 'ProjectBased',
    payRate: null,
    availability: null,
  },
  {
    id: 'troy',
    name: 'Troy',
    role: 'Project-Based',
    appRole: 'Team',
    employmentType: 'ProjectBased',
    payRate: null,
    availability: null,
  },
];
